services:
  webots:
    image: cyberbotics/webots:R2025a-ubuntu22.04
    container_name: webots
    network_mode: host
    privileged: true
    restart: unless-stopped

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - XAUTHORITY=/root/.Xauthority
      - WORLD_FILE=${WORLD_FILE:-/root/projects/worlds/tpbot.wbt}

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ./projects:/root/projects
      # - /dev/bus/usb:/dev/bus/usb

    shm_size: "512m"

    stdin_open: true
    tty: true

    command: >
      webots
      --mode=realtime
      --stdout
      --stderr
      ${WORLD_FILE:-/root/projects/worlds/tpbot.wbt}
      
